use_frameworks!

target 'LIPhotosKitManager_Example' do
  pod 'LIPhotosKitManager', :path => '../'

  target 'LIPhotosKitManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
